### ISSUE TITLE
Idea: add an optional "label" to a wallet 

### ISSUE THREAD

**Issue by freak12techno** [SmartStake/relayers#509]
In `chainsRelayed`, there's an array of objects, each having a `ticker` and a `relayerAddress` fields.
I think it would be nice to allow specifying some kind of a label/alias identifying this wallet.

My use case: so I am running 2 relayers, one with Hermes and one with rly, using different wallets.
When I go to the UI, I see something like this:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/fe24471f-73b6-41cc-a59a-4cba588afb63">
and without using the external data it's unclear which wallet is used by which relayer.

I propose doing the following:
1) adding the optional `alias` (or something similar) field to an entity in `chainsRelayed`
2) in UI, changing the text of the "Address" link to display either `alias`, if it's present, or `relayerAddress` if not (while the link should still lead to the wallet from `relayerAddress` field).

Should be pretty backwards-compatible this way.

What do you think?

**Comment by SmartStake** [comment]
Great idea. Agreed on adding it to the json object.

As you alluded to on the UI side, Smart stake works exactly like that. It has the concept of aliases in some of the other analytics/richlists. It shows alias in place of address where alias is present but the copy button (and perhaps hover/tooltip can still show address). 

will add to todo and rollout shortly. thanks for the suggestions.

**Comment by freak12techno** [comment]
Btw, on json object: I suggest adding a JSON schema and a CI action to validate it (this goes out of scope of this issue for sure, but just a thought it'd be nice)

**Comment by SmartStake** [comment]
Supported optional "alias" in github for wallets/addresses. will look into the JSON schema validation.
